version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852/NewGitTestProject
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.newgittest.integrations:TestExternalGit
  packages:
  - name: NewGitTestProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
