version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852/NewGitTestProject
  gitUsername: santhu736852
  gitBranch: main
- name: packageServiceValidations
  gitServerName: poanTestGit
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
- name: PackageTestdev2
  gitServerName: mraj_org
  gitUrl: https://github.webmethods.io/mraj
  gitUsername: mraj
  gitBranch: main
- name: CustomPackage
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: branch2
services:
- serviceName: project.newgittest.integrations:TestEG
  packages:
  - name: NewGitTestProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.1120
