version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitTestProject
  gitServerName: SanthoshKToken7D
  gitUrl: https://github.com/santhu736852/NewGitTestProject
  gitUsername: santhu736852
  gitBranch: main
